#!/bin/bash
echo 'U r going to play a videofile. Type the file path to continue:'
read name
if test -f "$name"; then
echo 'Choose framework: [1] ffmpeg [2] gstreamer'
read framen
case "$framen" in
1) ffplay "$name"
;;
2)gst-launch-1.0 playbin uri = "file://$name" 
;;
*) echo 'Wrong input.'
;;
esac
else
echo 'The file name typed wrong!'
fi
